# Generated by Django 6.0.1 on 2026-01-21 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('command_string', models.TextField(help_text='The actual FFmpeg command.')),
                ('explanation', models.TextField(help_text='Detailed breakdown of what the command does.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_command_string', models.TextField()),
                ('suggested_explanation', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_comment', models.TextField(blank=True, help_text='Reason for rejection or feedback.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='commands.command')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
